### ISSUE TITLE
 Missing commas separating Remotes: 'github::cran/FField

### ISSUE THREAD

**Issue by QAQD** [PNNL-Comp-Mass-Spec/MSnSet.utils#28]
The Rstudio keep reporting the following errors when I install this package:
Error: Failed to install 'MSnSet.utils' from GitHub:
  Missing commas separating Remotes: 'github::cran/FField
    github::PNNL-Comp-Mass-Spec/MSnID'

I want to know how to solve this problem.

**Comment by TylerSagendorf** [comment]
@QAQD This will be fixed once #29 is merged.
