### ISSUE TITLE
handling of missing values in column annotation by complex_heatmap

### ISSUE THREAD

**Issue by vladpetyuk** [PNNL-Comp-Mass-Spec/MSnSet.utils#40]
complex_heatmap [in this script](https://github.com/PNNL-Comp-Mass-Spec/r_script_sandbox/blob/1832eb5da2c06a2df0267fd101e7ec584f36dc18/microglia/maxquant_searches/read_and_save_maxquant_4857.R#L103) is crashing because some samples don't have DX annotation

**Comment by vladpetyuk** [comment]
proposed solution is to 
1. replace NA values with "NA" string
2. assign it some sort of shade of gray

**Comment by skelly001** [comment]
Seems like this has already been addressed, so closing. Linked script appears to be working properly
